name: Extension compilation

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: tabmortality-build
          path: |
            tabmortality.zip
